# Generated by Django 5.0 on 2023-12-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleMaster',
            fields=[
                ('sample_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('assessor_name', models.CharField(max_length=50)),
                ('date_collected', models.DateField(null=True)),
                ('date_measured', models.DateField(null=True)),
                ('location_code', models.CharField(max_length=10, null=True)),
                ('plankton_net_type', models.CharField(max_length=20, null=True)),
                ('bl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pdl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('snl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ed', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bd', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vafl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dorsal_count', models.IntegerField(null=True)),
                ('anal_count', models.IntegerField(null=True)),
                ('pectoral_count', models.IntegerField(null=True)),
                ('pelvic_count', models.IntegerField(null=True)),
                ('caudal_count', models.IntegerField(null=True)),
                ('vertebrae_count', models.IntegerField(null=True)),
                ('stage_name', models.CharField(max_length=50, null=True)),
                ('margin_no', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'sample_master',
            },
        ),
    ]
