# Generated by Django 5.0 on 2023-12-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemaster',
            name='assessor_name',
            field=models.CharField(max_length=50),
        ),
    ]
