# Generated by Django 5.0 on 2023-12-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='samplemaster',
            table=None,
        ),
    ]
