# Generated by Django 5.0 on 2023-12-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_samplemaster_assessor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemaster',
            name='sample_no',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
