# Generated by Django 5.0 on 2023-12-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_samplemaster_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='samplemaster',
            table='sample_master',
        ),
    ]
