# Generated by Django 5.0 on 2023-12-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_samplemaster_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplemaster',
            options={'managed': False},
        ),
    ]
