# Generated by Django 5.0 on 2024-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_familyscorecard_fishratio_genusscorecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeCharacteristicResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('fgroup_no', models.IntegerField(blank=True, null=True)),
                ('bd_characteristic', models.CharField(blank=True, max_length=20, null=True)),
                ('hl_characteristic', models.CharField(blank=True, max_length=20, null=True)),
                ('ed_characteristic', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'shape_characteristic_result',
                'managed': False,
            },
        ),
    ]
